package com.typeahead.startup;

import com.typeahead.cache.DistributedCache;
import com.typeahead.model.QueryFrequency;
import com.typeahead.repository.QueryFrequencyRepository;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

@Component
public class DataSeeder implements CommandLineRunner {
    private static final Logger log = LoggerFactory.getLogger(DataSeeder.class);

    private final QueryFrequencyRepository repository;
    private final DistributedCache distributedCache;

    @Value("${app.dataset.path}")
    private String datasetPath;

    public DataSeeder(QueryFrequencyRepository repository, DistributedCache distributedCache) {
        this.repository = repository;
        this.distributedCache = distributedCache;
    }

    @Override
    public void run(String... args) throws Exception {
        long existingCount = repository.count();
        if (existingCount > 0) {
            log.info("Database already contains {} queries, skipping dataset seeding.", existingCount);
        } else {
            loadDataset();
        }

        // Always build/refresh cache sharding on startup
        List<QueryFrequency> allQueries = repository.findAllByOrderByCountDesc();
        log.info("Starting initial cache construction for {} queries...", allQueries.size());
        long start = System.currentTimeMillis();
        distributedCache.buildFullCache(allQueries);
        log.info("Cache initialization completed in {} ms", (System.currentTimeMillis() - start));
    }

    private void loadDataset() {
        File file = new File(datasetPath);
        if (!file.exists()) {
            log.warn("Dataset CSV file not found at path: {}. Skipping database seed.", datasetPath);
            return;
        }

        log.info("Found dataset at: {}. Seeding database...", file.getAbsolutePath());
        long start = System.currentTimeMillis();

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {
            String line = br.readLine(); // Read and discard header: "query,count"
            List<QueryFrequency> batch = new ArrayList<>();
            long loadedCount = 0;

            while ((line = br.readLine()) != null) {
                int lastCommaIndex = line.lastIndexOf(',');
                if (lastCommaIndex == -1) {
                    continue; // Skip invalid lines
                }

                String query = line.substring(0, lastCommaIndex);
                // Unwrap quotes if generated by CSV writer
                if (query.startsWith("\"") && query.endsWith("\"")) {
                    query = query.substring(1, query.length() - 1);
                }
                query = query.toLowerCase().trim();

                long count;
                try {
                    count = Long.parseLong(line.substring(lastCommaIndex + 1).trim());
                } catch (NumberFormatException e) {
                    continue; // Skip malformed lines
                }

                batch.add(new QueryFrequency(query, count));
                loadedCount++;

                // Save in batches of 5000 records
                if (batch.size() >= 5000) {
                    repository.saveAll(batch);
                    batch.clear();
                    log.info("Seeded {} queries into SQL repository...", loadedCount);
                }
            }

            // Save remaining elements
            if (!batch.isEmpty()) {
                repository.saveAll(batch);
                batch.clear();
            }

            log.info("Successfully finished seeding {} records in {} ms", loadedCount, (System.currentTimeMillis() - start));

        } catch (IOException e) {
            log.error("Error reading dataset file", e);
        }
    }
}
