server.port=8080

# H2 Database Configurations
spring.datasource.url=jdbc:h2:mem:typeahead;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# JPA Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# Redis Configurations
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Application Custom Configurations
app.dataset.path=../dataset/seed_queries.csv
app.batch.flush-interval=5000
app.batch.queue-threshold=100
app.trending.weight=100
app.trending.decay-interval=60000
